[package]
name = "jqlang-parse"
version = "0.1.0"
edition = "2021"

[lib]
name = "jqlang_parse"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.2"
jqlang = { path = "../jqlang", version = "0.1.0" }
